// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function handler($$event) {
  console.log("event", JSON.stringify($$event));
  return $$event;
}

exports.handler = handler;
/* No side effect */
