let toString = t =>
  switch (t) {
  | `TAGGING => "TAGGING"
  | `ACCESSING => "ACCESSING"
  | `BOOKMARKING => "BOOKMARKING"
  | `CLASSIFYING => "CLASSIFYING"
  | `COMMENTING => "COMMENTING"
  | `DESCRIBING => "DESCRIBING"
  | `EDITING => "EDITING"
  | `HIGHLIGHTING => "HIGHLIGHTING"
  | `IDENTIFYING => "IDENTIFYING"
  | `LINKING => "LINKING"
  | `MODERATING => "MODERATING"
  | `QUESTIONING => "QUESTIONING"
  | `REPLYING => "REPLYING"
  };
