// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var getInstance = (function () {
    if (window) {
      return require("amplitude-js")
    } else {
      return {
        init: () => {},
        logWithEvent: () => {}
      }
    }
  });

exports.getInstance = getInstance;
/* No side effect */
