// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Observable = {};

function query(param) {
  return param.query;
}

function variables(param) {
  return param.variables;
}

function operationName(param) {
  return param.operationName;
}

function extensions(param) {
  return param.extensions;
}

function setContext(param) {
  return param.setContext;
}

function getContext(param) {
  return param.getContext;
}

function toKey(param) {
  return param.toKey;
}

exports.Observable = Observable;
exports.query = query;
exports.variables = variables;
exports.operationName = operationName;
exports.extensions = extensions;
exports.setContext = setContext;
exports.getContext = getContext;
exports.toKey = toKey;
/* No side effect */
