// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var ApolloLink = require("apollo-link");

function make(onOperation) {
  return new ApolloLink.ApolloLink((function (operation, forward) {
                return Js_option.some(Curry._1(forward, operation).map(function (data) {
                                Curry._2(onOperation, operation, data);
                                return data;
                              }));
              }));
}

exports.make = make;
/* apollo-link Not a pure module */
