#!/bin/bash
set -e

OWN_PATH=`realpath $0`
ROOT_DIR=`realpath "$(dirname $OWN_PATH)/../"`
AWS_PROFILE=amplify-literal
API_ID=to6hgjbvbjb7roq46jyzhxr2my 

aws appsync get-introspection-schema \
  --format JSON \
  --api-id $API_ID \
  --profile $AWS_PROFILE \
  "$ROOT_DIR/app/src/main/graphql/schema.json"

# Warning: overrites any manual tuning in autogenerated files
# amplify codegen
