type t = [
  | `TEXT_PLAIN
  | `TEXT_HTML
  | `APPLICATION_OCTET_STREAM
  | `APPLICATION_X_MIMEARCHIVE
  | `IMAGE_PNG
];

let toString = t =>
  switch (t) {
  | `TEXT_PLAIN => "TEXT_PLAIN"
  | `TEXT_HTML => "TEXT_HTML"
  | `APPLICATION_X_MIMEARCHIVE => "APPLICATION_X_MIMEARCHIVE"
  | `APPLICATION_OCTET_STREAM => "APPLICATION_OCTET_STREAM"
  | `IMAGE_PNG => "IMAGE_PNG"
  };
