// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function toString(t) {
  if (t === "TEXT_HTML") {
    return "TEXT_HTML";
  } else if (t === "APPLICATION_OCTET_STREAM") {
    return "APPLICATION_OCTET_STREAM";
  } else if (t === "TEXT_PLAIN") {
    return "TEXT_PLAIN";
  } else if (t === "APPLICATION_X_MIMEARCHIVE") {
    return "APPLICATION_X_MIMEARCHIVE";
  } else {
    return "IMAGE_PNG";
  }
}

exports.toString = toString;
/* No side effect */
