// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(t) {
  if (t === "HIGHLIGHTING") {
    return "HIGHLIGHTING";
  } else if (t === "BOOKMARKING") {
    return "BOOKMARKING";
  } else if (t === "DESCRIBING") {
    return "DESCRIBING";
  } else if (t === "COMMENTING") {
    return "COMMENTING";
  } else if (t === "IDENTIFYING") {
    return "IDENTIFYING";
  } else if (t === "REPLYING") {
    return "REPLYING";
  } else if (t === "ACCESSING") {
    return "ACCESSING";
  } else if (t === "QUESTIONING") {
    return "QUESTIONING";
  } else if (t === "CLASSIFYING") {
    return "CLASSIFYING";
  } else if (t === "LINKING") {
    return "LINKING";
  } else if (t === "EDITING") {
    return "EDITING";
  } else if (t === "TAGGING") {
    return "TAGGING";
  } else {
    return "MODERATING";
  }
}

exports.toString = toString;
/* No side effect */
