// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var _map = {"DATASET":"DATASET","IMAGE":"IMAGE","SOUND":"SOUND","TEXT":"TEXT","VIDEO":"VIDEO"};

function tToJs(param) {
  return param;
}

function tFromJs(param) {
  return _map[param];
}

var toJs = tToJs;

exports.tToJs = tToJs;
exports.tFromJs = tFromJs;
exports.toJs = toJs;
/* No side effect */
