// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(t) {
  if (t === "RTL") {
    return "RTL";
  } else if (t === "AUTO") {
    return "AUTO";
  } else {
    return "LTR";
  }
}

exports.toString = toString;
/* No side effect */
