// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function authWithCognitoUserPools(jwtToken) {
  return {
          type: "AMAZON_COGNITO_USER_POOLS",
          jwtToken: jwtToken
        };
}

function authWithIAM(credentials) {
  return {
          type: "AWS_IAM",
          credentials: credentials
        };
}

var Client = {
  authWithCognitoUserPools: authWithCognitoUserPools,
  authWithIAM: authWithIAM
};

var Rehydrated = {};

exports.Client = Client;
exports.Rehydrated = Rehydrated;
/* No side effect */
